apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aap-kalkulator
  namespace: aap
  labels:
    team: aap
spec:
  port: 8080
  image: {{ image }}
  idporten:
    enabled: true
    sidecar:
      enabled: true
  ingresses:
    - https://aap-kalkulator.dev.nav.no