apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aap-kalkulator
  namespace: aap
  labels:
    team: aap
spec:
  port: 8080
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: g.nav.no
  ingresses:
    - https://aap-kalkulator.dev.nav.no